<a href="https://colab.research.google.com/github/Aliyamkamila/Fundamental-Data-Science/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np


Array dengan rank 1 dan panjang 3.

In [2]:
[1,2,3]

[1, 2, 3]

Array dengan rank 2 dan panjang 3.

In [3]:
[[1,2,3], [4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [7]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


**ndarray**: nama class untuk sebuah numpy array

In [ ]:
a = np.array([1,2,3])

# Properties
* ndarray.ndim : dimensi dari sebuah numpy array.
* ndarray.shape : baris dan kolum dari sebuah numpyn array.
* ndarray.size : jumlah elemen di dalam numpy array.
* ndarray.dtype : tipe data dari elemen yg ada dinumpy array.
* ndarray.itemsize : ukuran elemen (bytes) yg ada di numpy array.
* ndarray.data : sebuah buffer untuk menyimpan elemen" di dlm numpy array.

In [8]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])



In [11]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [12]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


# Create Numpy Arrays

* np.zeros: isinya semua 0
* np.ones: isinya semua 1
* arange: bisa berikan scope dan panjang dari step
* np.linespace: berikan scope dan jumlah elemen yg diinginkan
* np.random.random: memberikan angka acak


In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.arange(1,2,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [22]:
np.linspace(1,3,6)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [23]:
np.random.random((3,3))

array([[0.31252851, 0.47077388, 0.30119726],
       [0.74007003, 0.10217122, 0.83015808],
       [0.22764205, 0.58650957, 0.54654012]])

# Shape and Operation


* reshape: mengubah dimensi/shape dari sebuah numpy array
* vstack: stack numpy arrays secara vertikal
* hstack: stack numpy arrays secara horizontal
* vsplit: split numpy array secara vertikal
* hsplit: split numpy array secara horizontal

In [38]:
a = np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
b = np.array([(7,8), (9,10)])
b

array([[ 7,  8],
       [ 9, 10]])

In [34]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [35]:
c = np.array([(11,12,13), (14,15,16)])
c

array([[11, 12, 13],
       [14, 15, 16]])

In [39]:
d =  np.hstack((a,c))
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [40]:
np.vsplit(d,2)

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [41]:
np.hsplit(d,3)

[array([[1, 2],
        [4, 5]]),
 array([[ 3, 11],
        [ 6, 14]]),
 array([[12, 13],
        [15, 16]])]

In [42]:
np.hsplit(d,(1,3)) # split after kolum 1 dan 3

[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]