<a href="https://colab.research.google.com/github/Aliyamkamila/Fundamental-Data-Science/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np


Array dengan rank 1 dan panjang 3.

In [2]:
[1,2,3]

[1, 2, 3]

Array dengan rank 2 dan panjang 3.

In [3]:
[[1,2,3], [4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [7]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


**ndarray**: nama class untuk sebuah numpy array

In [ ]:
a = np.array([1,2,3])

# Properties
* ndarray.ndim : dimensi dari sebuah numpy array.
* ndarray.shape : baris dan kolum dari sebuah numpyn array.
* ndarray.size : jumlah elemen di dalam numpy array.
* ndarray.dtype : tipe data dari elemen yg ada dinumpy array.
* ndarray.itemsize : ukuran elemen (bytes) yg ada di numpy array.
* ndarray.data : sebuah buffer untuk menyimpan elemen" di dlm numpy array.

In [8]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])



In [11]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [12]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


# Create Numpy Arrays

* np.zeros: isinya semua 0
* np.ones: isinya semua 1
* arange: bisa berikan scope dan panjang dari step
* np.linespace: berikan scope dan jumlah elemen yg diinginkan
* np.random.random: memberikan angka acak


In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.arange(1,2,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [22]:
np.linspace(1,3,6)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [23]:
np.random.random((3,3))

array([[0.31252851, 0.47077388, 0.30119726],
       [0.74007003, 0.10217122, 0.83015808],
       [0.22764205, 0.58650957, 0.54654012]])

# Shape and Operation


* reshape: mengubah dimensi/shape dari sebuah numpy array
* vstack: stack numpy arrays secara vertikal
* hstack: stack numpy arrays secara horizontal
* vsplit: split numpy array secara vertikal
* hsplit: split numpy array secara horizontal

In [38]:
a = np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
b = np.array([(7,8), (9,10)])
b

array([[ 7,  8],
       [ 9, 10]])

In [34]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [35]:
c = np.array([(11,12,13), (14,15,16)])
c

array([[11, 12, 13],
       [14, 15, 16]])

In [39]:
d =  np.hstack((a,c))
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [40]:
np.vsplit(d,2)

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [41]:
np.hsplit(d,3)

[array([[1, 2],
        [4, 5]]),
 array([[ 3, 11],
        [ 6, 14]]),
 array([[12, 13],
        [15, 16]])]

In [42]:
np.hsplit(d,(1,3)) # split after kolum 1 dan 3

[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

# Indexing

In [43]:
data = np.arange(100,200)
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [44]:
data[0]

100

In [52]:
fives = np.arange(0,100,5)
fives

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [53]:
data[fives]


array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [54]:
data2D = data.reshape(10,-1)
data2D

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [58]:
data2D [2]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [60]:
data2D[3,2]

132

In [64]:
data2D[-2,-1]

189

In [65]:
data2D[2,:]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [66]:
data2D[:,3]

array([103, 113, 123, 133, 143, 153, 163, 173, 183, 193])

In [69]:
data2D[1:4, 3:5]
# baris 1,2,3
# kolum 3 dan 4

array([[113, 114],
       [123, 124],
       [133, 134]])

# Mathematics

In [70]:
numbers = np.random.random((5,5))
numbers


array([[0.89816653, 0.08200987, 0.88998896, 0.38395229, 0.16056953],
       [0.975976  , 0.10557799, 0.46921131, 0.66517378, 0.59629654],
       [0.05245555, 0.27141399, 0.50715848, 0.11702209, 0.37364582],
       [0.71053717, 0.77333847, 0.8627723 , 0.5186272 , 0.52474567],
       [0.32504168, 0.69510665, 0.18074855, 0.64598042, 0.81568287]])

In [71]:
print(np.amin(numbers)) #minimum
print(np.amax(numbers)) #maximum
print(np.average(numbers)) #averange
print(np.sum(numbers))#rata"

0.05245555227619925
0.9759760007722399
0.5040479883380202
12.601199708450507


In [72]:
np.sqrt(numbers) #akar

array([[0.94771648, 0.28637365, 0.94339226, 0.61963883, 0.40071128],
       [0.98791498, 0.32492767, 0.68499   , 0.81558187, 0.7722024 ],
       [0.22903177, 0.52097408, 0.7121506 , 0.34208492, 0.61126576],
       [0.84293367, 0.87939665, 0.92885537, 0.72015776, 0.72439331],
       [0.57012426, 0.83373056, 0.42514532, 0.80372907, 0.90315163]])

In [73]:
#sin dr semua angka
np.sin(numbers)

array([[0.78218589, 0.08191797, 0.7770648 , 0.37458791, 0.15988044],
       [0.82824919, 0.10538196, 0.45218297, 0.61719587, 0.56158201],
       [0.0524315 , 0.26809394, 0.48569536, 0.11675519, 0.36501212],
       [0.65224105, 0.69852808, 0.7596484 , 0.49568833, 0.50099291],
       [0.31934828, 0.64046735, 0.17976598, 0.6019816 , 0.72819379]])

In [74]:
#cos
np.cos(numbers)

array([[0.62304513, 0.99663908, 0.62942061, 0.9271914 , 0.98713639],
       [0.56035995, 0.99443182, 0.8919252 , 0.78680954, 0.82742108],
       [0.99862452, 0.96339278, 0.87412815, 0.99316073, 0.93100277],
       [0.75801162, 0.71558265, 0.65033399, 0.86850048, 0.86545139],
       [0.94763742, 0.7679854 , 0.98370941, 0.79850995, 0.68537129]])

In [80]:
sample = np.arange (1,21)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
sample2 = np.arange (51,71)
sample2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

In [84]:
sample + sample2

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90])

In [86]:
sample2 - sample

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])

In [87]:
sample * sample2

array([  51,  104,  159,  216,  275,  336,  399,  464,  531,  600,  671,
        744,  819,  896,  975, 1056, 1139, 1224, 1311, 1400])

In [88]:
sample/sample2

array([0.01960784, 0.03846154, 0.05660377, 0.07407407, 0.09090909,
       0.10714286, 0.12280702, 0.13793103, 0.15254237, 0.16666667,
       0.18032787, 0.19354839, 0.20634921, 0.21875   , 0.23076923,
       0.24242424, 0.25373134, 0.26470588, 0.27536232, 0.28571429])

In [91]:
matrix = np.random.randint (1,50,20)
matrix

array([31, 16, 45, 11, 17, 26, 36,  4, 32, 45, 26, 10,  3, 27, 25, 19, 33,
       16, 41,  8])

In [92]:
matrix = matrix.reshape(4,-1)
matrix

array([[31, 16, 45, 11, 17],
       [26, 36,  4, 32, 45],
       [26, 10,  3, 27, 25],
       [19, 33, 16, 41,  8]])

In [93]:
matrix.transpose() #baris jd kolum, kolum jd baris

array([[31, 26, 26, 19],
       [16, 36, 10, 33],
       [45,  4,  3, 16],
       [11, 32, 27, 41],
       [17, 45, 25,  8]])

In [94]:
np.dot(matrix, -1)

array([[-31, -16, -45, -11, -17],
       [-26, -36,  -4, -32, -45],
       [-26, -10,  -3, -27, -25],
       [-19, -33, -16, -41,  -8]])