<a href="https://colab.research.google.com/github/Aliyamkamila/Fundamental-Data-Science/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np


Array dengan rank 1 dan panjang 3.

In [2]:
[1,2,3]

[1, 2, 3]

Array dengan rank 2 dan panjang 3.

In [3]:
[[1,2,3], [4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [7]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


**ndarray**: nama class untuk sebuah numpy array

In [ ]:
[ ] a = np.array([1,2,3])

# Properties
* ndarray.ndim : dimensi dari sebuah numpy array.
* ndarray.shape : baris dan kolum dari sebuah numpyn array.
* ndarray.size : jumlah elemen di dalam numpy array.
* ndarray.dtype : tipe data dari elemen yg ada dinumpy array.
* ndarray.itemsize : ukuran elemen (bytes) yg ada di numpy array.
* ndarray.data : sebuah buffer untuk menyimpan elemen" di dlm numpy array.

In [8]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])



In [11]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [12]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8
